{
 "title": "Go Runtime",
 "description": "Go runtime metrics from OpenTelemetry provider.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(go_goroutine_count,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "http", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "job" },
  {
   "title": "Total request count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(\n  increase(http_server_request_duration_seconds_count{job=\"translations\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status breakdown",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (\n  increase(\n    http_server_request_duration_seconds_count{job=~\"$job\"}[5m]\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "request per route",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "sum by (http_route)(\n  increase(http_server_request_duration_seconds_count{job=\"$job\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate < 500",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 *\n(\n  sum(\n    increase(\n      http_server_request_duration_seconds_count{\n        job=~\"$job\",\n        http_response_status_code=~\"5..\"\n      }[5m]\n    )\n  )\n  /\n  sum(\n    increase(\n      http_server_request_duration_seconds_count{job=~\"$job\"}[5m]\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per method",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum by (http_request_method)(\n  increase(http_server_request_duration_seconds_count{job=\"$job\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Processor Limit",
   "type": "timeseries",
   "description": "The number of OS threads that can execute user-level Go code simultaneously.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg by(job) (go_processor_limit{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutine leak detection",
   "type": "timeseries",
   "description": "Interpretation:\n\n~0 → healthy\n\nSlowly positive → leak\n\nSudden spike → burst fan-out or stuck workers",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "deriv(go_goroutine_count{job=\"$job\"}[10m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutine Count",
   "type": "timeseries",
   "description": "Count of live goroutines.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "avg by(job) (go_goroutine_count{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "description": "Memory used by the Go runtime.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(job) (avg by(job,go_memory_type) (go_memory_used_bytes{job=~\"$job\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stack Memory Used",
   "type": "timeseries",
   "description": "Memory used by the Go runtime.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(job) (go_memory_used_bytes{job=~\"$job\",go_memory_type=\"stack\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory GC Goal",
   "type": "timeseries",
   "description": "Heap size target for the end of the GC cycle.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(job) (go_memory_gc_goal_bytes{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Allocated",
   "type": "timeseries",
   "description": "Memory allocated to the heap by the application.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(job) (\n  increase(go_memory_allocated_bytes_total{job=~\"$job\"}[5m]) / 300\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Size Target",
   "type": "timeseries",
   "description": "Heap size target percentage configured by the user, otherwise 100.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(job) (go_config_gogc_percent{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Objects allocated per second",
   "type": "timeseries",
   "description": "High count + low bytes = lots of tiny allocations → classic Go perf smell.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "increase(go_memory_allocations_total{job=\"$job\"}[5m]) / 300\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}